version: '3.4'
services:
  web:
    image: odoo
    build:
      context: ./dockerfile
      dockerfile: odoo.Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo-config:/etc/odoo
      - ./custom-addons:/mnt/custom-addons
    restart: always

  db:
    image: postgres:13
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - 80:80
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data: